In [1]:
import pandas as pd
import numpy as np
from faker import Faker

fake = Faker()

np.random.seed(42)

In [3]:
# Generate Customer Dataset
customers=[]

for i in range(1,1001):

    customers.append({

        "customer_id":i,

        "age":np.random.randint(18,60),

        "monthly_income":np.random.randint(10000,150000),

        "occupation":np.random.choice([
            "Student",
            "Teacher",
            "Engineer",
            "Driver",
            "Shop Owner",
            "Freelancer"
        ]),

        "city":fake.city(),

        "state":np.random.choice([
            "Maharashtra",
            "Gujarat",
            "Karnataka",
            "Delhi",
            "Telangana"
        ])
    })

customer_df=pd.DataFrame(customers)

customer_df.head()

   customer_id  age  monthly_income  occupation            city      state
0            1   56          141932    Engineer  Port Davidfort  Telangana
1            2   38           64886     Teacher   East Tonystad  Karnataka
2            3   40           97498  Shop Owner    Port Heather      Delhi
3            4   57           26023    Engineer       Ellisview  Telangana
4            5   19           69735      Driver      Goldenberg    Gujarat

In [5]:
# save customer data
customer_df.to_csv(
    "../data/customers.csv",
    index=False
)

print("customers.csv saved")

customers.csv saved

In [7]:
# Generate UPI Dataset
upi=[]

for customer in customer_df["customer_id"]:

    upi.append({

        "customer_id":customer,

        "txn_count":
        np.random.randint(20,300),

        "avg_transaction":
        np.random.randint(50,5000),

        "grocery_spend":
        np.random.randint(500,10000),

        "fuel_spend":
        np.random.randint(0,5000),

        "shopping_spend":
        np.random.randint(500,15000)

    })

upi_df=pd.DataFrame(upi)

upi_df.head()

,customer_id,txn_count,avg_transaction,grocery_spend,fuel_spend,shopping_spend
0,1,148,245,2687,3515,2830
1,2,253,3656,8968,60,12082
2,3,71,3977,6796,2591,9258
3,4,55,4767,6621,1200,13101
4,5,116,1286,7472,136,1529

In [9]:
# Save UPI Dataset
upi_df.to_csv(
    "../data/upi.csv",
    index=False)
print("upi.csv saved")

upi.csv saved

In [11]:
# Generate Utility Dataset
utility=[]

for customer in customer_df["customer_id"]:

    utility.append({

        "customer_id":customer,

        "electricity_bill":
        np.random.randint(300,3000),

        "internet_bill":
        np.random.randint(300,1500),

        "delay_days":
        np.random.randint(0,30)

    })

utility_df=pd.DataFrame(utility)

utility_df.head()

   customer_id  electricity_bill  internet_bill  delay_days
0            1              2072            899          10
1            2              2534           1025          14
2            3              2758           1255           8
3            4              1375           1351           0
4            5              1674           1288          17

In [13]:
# Save Utility Dataset
utility_df.to_csv(
    "../data/utility.csv",
    index=False
)

print("utility.csv saved")

utility.csv saved

In [15]:
# Generate Mobile Dataset
mobile=[]

for customer in customer_df["customer_id"]:

    mobile.append({

        "customer_id":customer,

        "recharge_frequency":
        np.random.randint(1,10),

        "monthly_data_usage":
        np.random.randint(1,100),

        "call_minutes":
        np.random.randint(50,2000)

    })

mobile_df=pd.DataFrame(mobile)

mobile_df.head()

   customer_id  recharge_frequency  monthly_data_usage  call_minutes
0            1                   8                  78           692
1            2                   1                  67          1455
2            3                   6                  19           788
3            4                   6                  69           571
4            5                   9                  33           446

In [17]:
# Save Mobile Dataset
mobile_df.to_csv(
    "../data/mobile.csv",
    index=False)

print("mobile.csv saved")

mobile.csv saved

In [19]:
import os

print(os.listdir("../data"))

['.ipynb_checkpoints', 'customers.csv', 'final_dataset.csv', 'mobile.csv', 'upi.csv', 'utility.csv']